apiVersion: v1
kind: Pod
metadata:
  name: cov-prev-ctl
spec:
  containers:
  - name: cov-prev-ctl
    image: 979276261708.dkr.ecr.ca-central-1.amazonaws.com/covprev-ctl
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim